---
# tasks file for pingDL
#

  - name: inovation
    action:
      "{{ (ansible_facts['os_family'] != 'Windows') | ternary('pingd', 'win_ping') }}"
    register: tictac

   - name: debug
     debug:
       var: tictac
