---
# tasks file for pingDL
#

  - name: inovation
    action:
      "{{ (ansible_facts['os_family'] != 'Windows') | ternary('pingDL', 'win_ping') }}"
    register: tictac
    
   - name: debug
     debug:
       var: tictac

